bienvenidos a mis proyectos de ALONXO12364 
proyecto 1 Creación de portafolio personal
proyecto 2 Notebook Vocab Update 1
me llamo fermin estoy actualmente no desidiso en una carrera 
no me interesa nada realmente
mis intereses son la high school y l el basquetboll
mis metas son tener dinero a como de lugar
